import { StrictMode, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, ShoppingBag, Plus, Minus, X, ArrowRight, Truck, ShieldCheck, Sparkles, ChevronRight, Ruler, Package, CheckCircle2 } from 'lucide-react';
import { money, products, type Product } from './catalogue';
import './styles.css';

type CartLine = { product: Product; quantity: number };

function App() {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const [selected, setSelected] = useState<Product | null>(null);
  const [cart, setCart] = useState<CartLine[]>([]);
  const [cartOpen, setCartOpen] = useState(false);
  const categories = ['All', ...Array.from(new Set(products.map(p => p.category)))];
  const filtered = useMemo(() => products.filter(p => (category === 'All' || p.category === category) && `${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  const cartCount = cart.reduce((sum, line) => sum + line.quantity, 0);
  const subtotal = cart.reduce((sum, line) => sum + line.product.price * line.quantity, 0);
  const add = (product: Product, quantity = 1) => setCart(current => { const found = current.find(x => x.product.id === product.id); return found ? current.map(x => x.product.id === product.id ? { ...x, quantity: x.quantity + quantity } : x) : [...current, { product, quantity }]; });
  const change = (id: string, delta: number) => setCart(current => current.map(x => x.product.id === id ? { ...x, quantity: x.quantity + delta } : x).filter(x => x.quantity > 0));

  return <div className="min-h-screen bg-[#f7f7f5] text-slate-900">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur-xl">
      <div className="mx-auto flex max-w-[1440px] items-center gap-6 px-5 py-4 lg:px-10">
        <button onClick={() => { setCategory('All'); setSelected(null); window.scrollTo({ top: 0, behavior: 'smooth' }); }} className="mr-auto min-w-fit text-left"><div className="text-xl font-black tracking-[-.04em]">AVA <span className="text-indigo-600">SURFACE</span></div><div className="text-[9px] font-bold uppercase tracking-[.32em] text-slate-400">Architectural surfaces</div></button>
        <div className="hidden max-w-2xl flex-1 lg:block"><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50/80 px-4 transition focus-within:border-indigo-400 focus-within:bg-white"><Search size={18} className="text-slate-400"/><input className="w-full bg-transparent py-3 text-sm outline-none" placeholder="Search products, SKU or collection..." value={query} onChange={e => setQuery(e.target.value)} /></div></div>
        <button onClick={() => setCartOpen(true)} className="relative flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><ShoppingBag size={18}/><span className="hidden sm:inline">Cart</span>{cartCount > 0 && <span className="rounded-full bg-indigo-600 px-2 py-0.5 text-[10px] text-white">{cartCount}</span>}</button>
      </div>
      <div className="mx-auto flex max-w-[1440px] gap-2 overflow-x-auto px-5 pb-4 lg:px-10">{categories.map(c => <button key={c} onClick={() => { setCategory(c); setSelected(null); }} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold transition ${category === c ? 'bg-slate-950 text-white shadow-sm' : 'text-slate-500 hover:bg-slate-100 hover:text-slate-900'}`}>{c}</button>)}</div>
      <div className="px-5 pb-4 lg:hidden"><div className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-slate-50 px-3"><Search size={18} className="text-slate-400"/><input className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder="Search products..." value={query} onChange={e => setQuery(e.target.value)} /></div></div>
    </header>

    <main className="mx-auto max-w-[1440px] px-5 pb-16 lg:px-10">
      <section className="relative mt-6 overflow-hidden rounded-[2rem] bg-slate-950 px-7 py-10 text-white shadow-xl sm:px-10 lg:mt-8 lg:px-14 lg:py-14"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-indigo-500/20 blur-3xl"/><div className="relative max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.2em] text-slate-300"><Sparkles size={13}/> Curated surface collection</div><h1 className="text-4xl font-black leading-[1.05] tracking-[-.045em] sm:text-5xl lg:text-6xl">Surfaces that define<br/><span className="text-indigo-300">better spaces.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-slate-300 sm:text-base">Premium tiles for homes, hospitality and commercial projects. Explore the collection and order directly from AVA Surface.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={() => setCategory('All')} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-xs font-black text-slate-950">Explore collection <ArrowRight size={15}/></button><span className="inline-flex items-center rounded-xl border border-white/15 px-4 py-3 text-xs font-bold text-slate-300">{products.length} products available</span></div></div></section>
      <section className="grid gap-4 py-8 sm:grid-cols-3"><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4"><Truck size={20} className="text-indigo-600"/><div><div className="text-xs font-black">Reliable delivery</div><div className="text-[11px] text-slate-400">Transport calculated at checkout</div></div></div><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4"><ShieldCheck size={20} className="text-indigo-600"/><div><div className="text-xs font-black">Secure ordering</div><div className="text-[11px] text-slate-400">Transparent pricing & payment</div></div></div><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4"><Sparkles size={20} className="text-indigo-600"/><div><div className="text-xs font-black">Built for projects</div><div className="text-[11px] text-slate-400">Retail and professional buyers</div></div></div></section>
      <div className="mb-5 flex items-end"><div className="mr-auto"><p className="text-[10px] font-black uppercase tracking-[.2em] text-indigo-600">Shop collection</p><h2 className="mt-1 text-2xl font-black tracking-tight">Featured surfaces</h2></div><span className="text-xs font-semibold text-slate-400">{filtered.length} results</span></div>
      {filtered.length === 0 ? <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-16 text-center text-slate-500">No products match your search.</div> : <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map(product => <article key={product.id} onClick={() => setSelected(product)} className="group cursor-pointer overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="relative h-60 overflow-hidden" style={{ background: product.accent }}><div className="absolute inset-0 opacity-25" style={{ backgroundImage: 'linear-gradient(30deg, transparent 45%, rgba(255,255,255,.7) 46%, transparent 48%), linear-gradient(120deg, transparent 45%, rgba(0,0,0,.12) 46%, transparent 48%)', backgroundSize: '52px 52px' }}/><span className="absolute left-4 top-4 rounded-full bg-white/80 px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-slate-700 backdrop-blur">{product.category}</span><button onClick={e => { e.stopPropagation(); add(product); }} className="absolute bottom-4 right-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-950 text-white opacity-0 shadow-lg transition group-hover:opacity-100"><Plus size={19}/></button></div><div className="p-5"><div className="text-[10px] font-bold tracking-wider text-slate-400">{product.sku}</div><h3 className="mt-1 min-h-10 text-sm font-black leading-5">{product.name}</h3><div className="mt-5 flex items-end justify-between"><div><div className="text-xl font-black tracking-tight">{money(product.price)}</div><div className="mt-0.5 text-[10px] font-medium text-slate-400">per {product.unit} · {product.stock} in stock</div></div><button onClick={e => { e.stopPropagation(); add(product); }} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black transition hover:border-indigo-600 hover:bg-indigo-600 hover:text-white">Add</button></div></div></article>)}</div>}
    </main>

    {selected && <div className="fixed inset-0 z-40"><div className="absolute inset-0 bg-slate-950/60 backdrop-blur-sm" onClick={() => setSelected(null)}/><section className="absolute left-1/2 top-1/2 max-h-[90vh] w-[calc(100%-2rem)] max-w-4xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-[2rem] bg-white shadow-2xl"><div className="grid lg:grid-cols-2"><div className="relative min-h-72 lg:min-h-[520px]" style={{ background: selected.accent }}><div className="absolute inset-0 opacity-25" style={{ backgroundImage: 'linear-gradient(30deg, transparent 45%, rgba(255,255,255,.7) 46%, transparent 48%), linear-gradient(120deg, transparent 45%, rgba(0,0,0,.12) 46%, transparent 48%)', backgroundSize: '64px 64px' }}/><button onClick={() => setSelected(null)} className="absolute right-4 top-4 rounded-xl bg-white/80 p-2 backdrop-blur"><X size={18}/></button></div><div className="p-7 sm:p-10"><div className="text-[10px] font-black uppercase tracking-[.2em] text-indigo-600">{selected.category} · {selected.sku}</div><h2 className="mt-3 text-3xl font-black leading-tight tracking-[-.03em]">{selected.name}</h2><div className="mt-4 text-3xl font-black">{money(selected.price)} <span className="text-sm font-semibold text-slate-400">/ {selected.unit}</span></div><div className="mt-6 grid grid-cols-2 gap-3">{selected.dimensions && <div className="rounded-xl bg-slate-50 p-3"><Ruler size={16} className="text-indigo-600"/><div className="mt-2 text-[10px] text-slate-400">Dimensions</div><div className="text-xs font-black">{selected.dimensions}</div></div>}{selected.finish && <div className="rounded-xl bg-slate-50 p-3"><Sparkles size={16} className="text-indigo-600"/><div className="mt-2 text-[10px] text-slate-400">Finish</div><div className="text-xs font-black">{selected.finish}</div></div>}{selected.pcsPerBox && <div className="rounded-xl bg-slate-50 p-3"><Package size={16} className="text-indigo-600"/><div className="mt-2 text-[10px] text-slate-400">Pieces / box</div><div className="text-xs font-black">{selected.pcsPerBox}</div></div>}{selected.sqftPerBox && <div className="rounded-xl bg-slate-50 p-3"><Ruler size={16} className="text-indigo-600"/><div className="mt-2 text-[10px] text-slate-400">Coverage / box</div><div className="text-xs font-black">{selected.sqftPerBox} sq.ft</div></div>}</div><div className="mt-5 flex items-center gap-2 text-xs font-bold text-emerald-600"><CheckCircle2 size={16}/> {selected.stock} units currently available</div><button onClick={() => { add(selected); setSelected(null); setCartOpen(true); }} className="mt-7 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 py-4 text-sm font-black text-white hover:bg-indigo-600">Add to cart <ArrowRight size={16}/></button></div></div></section></div>}

    {cartOpen && <div className="fixed inset-0 z-50"><div className="absolute inset-0 bg-slate-950/50 backdrop-blur-sm" onClick={() => setCartOpen(false)}/><aside className="absolute right-0 top-0 h-full w-full max-w-md overflow-y-auto bg-white shadow-2xl"><div className="flex items-center border-b border-slate-200 p-6"><div><h2 className="text-xl font-black">Your cart</h2><p className="mt-0.5 text-xs text-slate-400">{cartCount} item{cartCount === 1 ? '' : 's'}</p></div><button onClick={() => setCartOpen(false)} className="ml-auto rounded-xl p-2 hover:bg-slate-100"><X size={20}/></button></div>{cart.length === 0 ? <div className="p-10 text-center text-slate-500">Your cart is empty.</div> : <><div className="divide-y divide-slate-100">{cart.map(line => <div key={line.product.id} className="p-6"><div className="font-bold text-sm leading-5">{line.product.name}</div><div className="mt-1 text-[11px] text-slate-400">{line.product.sku} · {money(line.product.price)} / {line.product.unit}</div><div className="mt-4 flex items-center gap-3"><button onClick={() => change(line.product.id, -1)} className="rounded-lg border p-1.5"><Minus size={14}/></button><span className="w-7 text-center text-sm font-black">{line.quantity}</span><button onClick={() => change(line.product.id, 1)} className="rounded-lg border p-1.5"><Plus size={14}/></button><span className="ml-auto font-black">{money(line.product.price * line.quantity)}</span></div></div>)}</div><div className="border-t border-slate-200 p-6"><div className="flex justify-between text-sm"><span className="text-slate-500">Subtotal</span><strong>{money(subtotal)}</strong></div><div className="mt-2 flex justify-between text-xs text-slate-400"><span>Handling & transport</span><span>Calculated at checkout</span></div><button disabled className="mt-6 w-full rounded-2xl bg-slate-950 py-3.5 text-sm font-black text-white disabled:opacity-50">Proceed to checkout</button></div></>}</aside></div>}
  </div>;
}

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
